from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Calculator(object):
    def setupUi(self, Calculator):
        Calculator.setObjectName("Calculator")
        Calculator.resize(400, 500)
        self.centralwidget = QtWidgets.QWidget(Calculator)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 110, 361, 311))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_sub = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_sub.setObjectName("pushButton_sub")
        self.gridLayout.addWidget(self.pushButton_sub, 2, 4, 1, 1)
        self.pushButton_1 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_1.setObjectName("pushButton_1")
        self.gridLayout.addWidget(self.pushButton_1, 1, 0, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout.addWidget(self.pushButton_5, 2, 1, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout.addWidget(self.pushButton_7, 3, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 1, 1, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout.addWidget(self.pushButton_6, 2, 3, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout.addWidget(self.pushButton_4, 2, 0, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 1, 3, 1, 1)
        self.pushButton_0 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_0.setObjectName("pushButton_0")
        self.gridLayout.addWidget(self.pushButton_0, 4, 1, 1, 1)
        self.pushButton_calc = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_calc.setObjectName("pushButton_calc")
        self.gridLayout.addWidget(self.pushButton_calc, 4, 3, 1, 1)
        self.pushButton_add = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_add.setObjectName("pushButton_add")
        self.gridLayout.addWidget(self.pushButton_add, 1, 4, 1, 1)
        self.pushButton_mult = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_mult.setObjectName("pushButton_mult")
        self.gridLayout.addWidget(self.pushButton_mult, 3, 4, 1, 1)
        self.pushButton_8 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout.addWidget(self.pushButton_8, 3, 1, 1, 1)
        self.pushButton_div = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_div.setObjectName("pushButton_div")
        self.gridLayout.addWidget(self.pushButton_div, 4, 4, 1, 1)
        self.pushButton_9 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout.addWidget(self.pushButton_9, 3, 3, 1, 1)
        self.pushButton_dot = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_dot.setObjectName("pushButton_dot")
        self.gridLayout.addWidget(self.pushButton_dot, 4, 0, 1, 1)
        self.pushButton_clear = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_clear.setObjectName("pushButton_clear")
        self.gridLayout.addWidget(self.pushButton_clear, 0, 4, 1, 1)
        self.output = QtWidgets.QLabel(self.centralwidget)
        self.output.setGeometry(QtCore.QRect(20, 50, 361, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(26)
        self.output.setFont(font)
        self.output.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.output.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.output.setObjectName("output")
        Calculator.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Calculator)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 400, 22))
        self.menubar.setObjectName("menubar")
        self.menuType = QtWidgets.QMenu(self.menubar)
        self.menuType.setObjectName("menuType")
        Calculator.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Calculator)
        self.statusbar.setObjectName("statusbar")
        Calculator.setStatusBar(self.statusbar)
        self.actionNormal = QtWidgets.QAction(Calculator)
        self.actionNormal.setObjectName("actionNormal")
        self.actionScientific = QtWidgets.QAction(Calculator)
        self.actionScientific.setObjectName("actionScientific")
        self.menuType.addAction(self.actionNormal)
        self.menuType.addAction(self.actionScientific)
        self.menubar.addAction(self.menuType.menuAction())

        self.retranslateUi(Calculator)
        QtCore.QMetaObject.connectSlotsByName(Calculator)

        self.pushButton_0.clicked.connect(lambda: self.buf('0'))
        self.pushButton_1.clicked.connect(lambda: self.buf("1"))
        self.pushButton_2.clicked.connect(lambda: self.buf("2"))
        self.pushButton_3.clicked.connect(lambda: self.buf("3"))
        self.pushButton_4.clicked.connect(lambda: self.buf("4"))
        self.pushButton_5.clicked.connect(lambda: self.buf("5"))
        self.pushButton_6.clicked.connect(lambda: self.buf("6"))
        self.pushButton_7.clicked.connect(lambda: self.buf("7"))
        self.pushButton_8.clicked.connect(lambda: self.buf("8"))
        self.pushButton_9.clicked.connect(lambda: self.buf("9"))
        self.pushButton_div.clicked.connect(lambda: self.buf("/"))
        self.pushButton_mult.clicked.connect(lambda: self.buf("*"))
        self.pushButton_add.clicked.connect(lambda: self.buf("+"))
        self.pushButton_sub.clicked.connect(lambda: self.buf("-"))
        self.pushButton_dot.clicked.connect(lambda: self.buf("."))
        self.pushButton_clear.clicked.connect(self.clearout)
        self.pushButton_calc.clicked.connect(self.calculate)

    def clearout(self):
        self.output.setText("0")
        self.output.repaint()

    def calculate(self):
        ini = self.output.text()
        nums = []
        syms = []
        prev = 0
        for i in range(len(ini)):
            if ini[i] in ["+", "-", "/", "*"]:
                syms.append(ini[i])
                nums.append(float(ini[prev:i]))
                prev = i+1
        nums.append(int(ini[prev:]))
        out = ""
        for i in range(len(nums)):
            out += str(nums[i])
            if i < len(syms):
                out += syms[i]
        self.output.setText(str(eval(out)))
        self.output.repaint()

    def buf(self, oper):
        ini = self.output.text()
        if ini != "0":
            self.output.setText(ini + oper)
            self.output.repaint()
        else:
            self.output.setText(oper)
            self.output.repaint()

    def retranslateUi(self, Calculator):
        _translate = QtCore.QCoreApplication.translate
        Calculator.setWindowTitle(_translate("Calculator", "Calculator"))
        self.pushButton_sub.setText(_translate("Calculator", "-"))
        self.pushButton_1.setText(_translate("Calculator", "1"))
        self.pushButton_5.setText(_translate("Calculator", "5"))
        self.pushButton_7.setText(_translate("Calculator", "7"))
        self.pushButton_2.setText(_translate("Calculator", "2"))
        self.pushButton_6.setText(_translate("Calculator", "6"))
        self.pushButton_4.setText(_translate("Calculator", "4"))
        self.pushButton_3.setText(_translate("Calculator", "3"))
        self.pushButton_0.setText(_translate("Calculator", "0"))
        self.pushButton_add.setText(_translate("Calculator", "+"))
        self.pushButton_mult.setText(_translate("Calculator", "x"))
        self.pushButton_calc.setText(_translate("Calculator", "="))
        self.pushButton_8.setText(_translate("Calculator", "8"))
        self.pushButton_div.setText(_translate("Calculator", "/"))
        self.pushButton_9.setText(_translate("Calculator", "9"))
        self.pushButton_clear.setText(_translate("Calculator", "Clear"))
        self.pushButton_dot.setText(_translate("Calculator", "."))
        self.output.setText(_translate("Calculator", "0"))
        self.menuType.setTitle(_translate("Calculator", "Type"))
        self.actionNormal.setText(_translate("Calculator", "Normal"))
        self.actionScientific.setText(_translate("Calculator", "Scientific"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Calculator = QtWidgets.QMainWindow()
    ui = Ui_Calculator()
    ui.setupUi(Calculator)
    Calculator.show()
    sys.exit(app.exec_())
